export type EnrollmentHint = { english: string; manglish: string };

/** Short, plain-language help shown beside the enrollment step currently open. */
export const ENROLLMENT_HINTS: Record<string, EnrollmentHint> = {
  joiningDate: { english: "Enter your actual first working day.", manglish: "Ningal work thudangiya yathartha date nalkuka." },
  clientName: { english: "Select the client/site where you will be deployed.", manglish: "Ningal deploy cheyyunna client/site select cheyyuka." },
  resourceIdNumber: { english: "Enter the client-issued resource ID when required.", manglish: "Client thanna resource ID avashyamullappol nalkuka." },
  profilePicture: { english: "Upload a recent, clear passport-size photo.", manglish: "Puthiya, clear passport-size photo upload cheyyuka." },
  fullNameInput: { english: "Enter your full name exactly as on your official record.", manglish: "Official record-il ullathupole full peru ezhuthuka." },
  firstName: { english: "Enter your given name.", manglish: "Ningalude first/given name nalkuka." },
  lastName: { english: "Enter your family name or surname.", manglish: "Family name/surname nalkuka." },
  fatherName: { english: "Enter your father’s full name as on your proof.", manglish: "Proof-il ullathupole achante full peru nalkuka." },
  motherName: { english: "Enter your mother’s full name.", manglish: "Ammede full peru nalkuka." },
  dateOfBirth: { english: "Use the date shown on your official proof.", manglish: "Official proof-il ullathaya janana theeyathi nalkuka." },
  gender: { english: "Select the option that describes you.", manglish: "Ningalkku anuyojyamaya option select cheyyuka." },
  maritalStatus: { english: "Select your current marital status.", manglish: "Ippozhathe marital status select cheyyuka." },
  spouseName: { english: "If married, enter your spouse’s full name.", manglish: "Married aanenkil spouse-inte full peru nalkuka." },
  educationalQualification: { english: "Select your highest completed qualification.", manglish: "Poorthiyakkiya ettavum uyarnna qualification select cheyyuka." },
  otherQualification: { english: "Describe the qualification if you chose other.", manglish: "Other select cheythal qualification vivarikkuka." },
  lngJobDesignation: { english: "Select the designation for the LNG site.", manglish: "LNG site-ilulla designation select cheyyuka." },
  serviceBookNumber: { english: "Enter the service book number if your designation requires it.", manglish: "Designation avashyamanel service book number nalkuka." },
  serviceBookDocument: { english: "Upload the service book page clearly.", manglish: "Service book page clear ayi upload cheyyuka." },
  armsLicenseNumber: { english: "Enter the valid arms licence number when applicable.", manglish: "Applicable aanenkil valid arms licence number nalkuka." },
  armsLicenseDocument: { english: "Upload the valid arms licence copy.", manglish: "Valid arms licence copy upload cheyyuka." },
  passportCountryName: { english: "Enter the passport country only when applicable.", manglish: "Applicable aanenkil mathram passport country nalkuka." },
  passportDocument: { english: "Upload the passport copy when passport details are provided.", manglish: "Passport details nalkiyal passport copy upload cheyyuka." },
  district: { english: "Select or type your current district of residence.", manglish: "Ippol thamasikkunna district select/type cheyyuka." },
  panNumber: { english: "Enter the 10-character PAN exactly as printed.", manglish: "PAN card-il ullathupole 10-character number nalkuka." },
  aadharNumber: { english: "Enter the 12-digit Aadhaar number; it is used only for ESIC/EPF and statutory processing.", manglish: "12-digit Aadhaar number nalkuka; ESIC/EPF statutory processing vendi mathram." },
  nationality: { english: "Enter your nationality as shown in your records.", manglish: "Records-il ullathupole nationality nalkuka." },
  identificationMark: { english: "Describe a visible identification mark.", manglish: "Kaanaan pattunna identification mark vivarikkuka." },
  heightCm: { english: "Enter your height in centimetres.", manglish: "Height centimetre-il nalkuka." },
  weightKg: { english: "Enter your weight in kilograms.", manglish: "Weight kilogram-il nalkuka." },
  identityProofType: { english: "Choose one identity proof: PAN, Voter ID, Driving Licence, Passport, School Certificate, or Birth Certificate.", manglish: "Identity proof aayi PAN, Voter ID, Driving Licence, Passport, School Certificate, allenkil Birth Certificate select cheyyuka." },
  identityProofNumber: { english: "Enter the number printed on the selected identity proof.", manglish: "Select cheytha identity proof-ilulla number nalkuka." },
  identityProofUrlFront: { english: "Upload the front side of the identity proof.", manglish: "Identity proof-inte front side upload cheyyuka." },
  identityProofUrlBack: { english: "Upload the back side of the identity proof.", manglish: "Identity proof-inte back side upload cheyyuka." },
  addressProofType: { english: "Choose a different address proof: Voter ID, Passport, or Driving Licence.", manglish: "Identity proof-il ninn vyathyasthamaya Voter ID, Passport, allenkil Driving Licence select cheyyuka." },
  addressProofNumber: { english: "Enter the number printed on the selected address proof.", manglish: "Address proof-ilulla number nalkuka." },
  addressProofUrlFront: { english: "Upload the front side of the address proof.", manglish: "Address proof-inte front side upload cheyyuka." },
  addressProofUrlBack: { english: "Upload the back side of the address proof.", manglish: "Address proof-inte back side upload cheyyuka." },
  aadharCardDocument: { english: "Upload a clear self-attested Aadhaar copy for ESIC/EPF only.", manglish: "ESIC/EPF vendi mathram clear self-attested Aadhaar copy upload cheyyuka." },
  panCardDocument: { english: "Upload the PAN copy when required for the selected client.", manglish: "Selected client avashyamanel PAN copy upload cheyyuka." },
  signatureUrl: { english: "Sign on white paper and upload a clear image.", manglish: "Velutha paper-il sign cheythu clear image upload cheyyuka." },
  policeClearanceCertificate: { english: "Upload the PCC if available or requested.", manglish: "PCC undenkil/allenkil request cheythal upload cheyyuka." },
  epfUanNumber: { english: "Enter your existing EPF UAN, if any.", manglish: "Existing EPF UAN undenkil nalkuka." },
  esicNumber: { english: "Enter your existing ESIC number, if any.", manglish: "Existing ESIC number undenkil nalkuka." },
  bankAccountNumber: { english: "Enter the bank account used for salary credit.", manglish: "Salary varunna bank account number nalkuka." },
  ifscCode: { english: "Enter the 11-character IFSC from your bank document.", manglish: "Bank document-ilulla 11-character IFSC nalkuka." },
  bankName: { english: "Enter the full bank name.", manglish: "Bank-inte full peru nalkuka." },
  branchName: { english: "Enter the branch name shown on the bank proof.", manglish: "Bank proof-il ullathaya branch peru nalkuka." },
  bankPassbookStatement: { english: "Upload a clear passbook or statement showing account details.", manglish: "Account details kaanikkunna clear passbook/statement upload cheyyuka." },
  fullAddress: { english: "Enter your complete current address, including PIN code.", manglish: "PIN code ulppedeyulla complete current address nalkuka." },
  emailAddress: { english: "Enter an email you can access for official updates.", manglish: "Official updates kittan ningal access cheyyunna email nalkuka." },
  phoneNumber: { english: "Enter your active 10-digit mobile number.", manglish: "Ippol upayogikkunna 10-digit mobile number nalkuka." },
  legacyUniqueId: { english: "Use the existing LNG ID only when one was already assigned.", manglish: "Munpu assign cheytha LNG ID undenkil mathram nalkuka." },
  termsAndConditions: { english: "Read the terms, duties, verification, and statutory-rights notice before accepting.", manglish: "Terms, duties, verification, statutory rights notice vaayichittu accept cheyyuka." },
  aadhaarConsentAccepted: { english: "Consent is limited to ESIC, EPF, and related statutory processing through official systems.", manglish: "Aadhaar consent ESIC, EPF, related statutory processing official systems vazhi mathram aanu." },
  guardUndertakingAccepted: { english: "Read and accept the Guard Undertaking; it does not waive your statutory rights.", manglish: "Guard Undertaking vaayichu accept cheyyuka; statutory rights waive cheyyunnilla." },
};

export function getEnrollmentHint(field: string) {
  return ENROLLMENT_HINTS[field];
}
