/** Human-facing names used when the form points to missing information. */
const ENROLLMENT_FIELD_LABELS: Record<string, string> = {
  joiningDate: "Joining date",
  clientName: "Client or work site",
  resourceIdNumber: "Client resource ID",
  profilePicture: "Profile photo",
  fullNameInput: "Full name",
  firstName: "First name",
  lastName: "Last name",
  fatherName: "Father's name",
  motherName: "Mother's name",
  dateOfBirth: "Date of birth",
  gender: "Gender",
  maritalStatus: "Marital status",
  spouseName: "Spouse's name",
  educationalQualification: "Highest qualification",
  otherQualification: "Other qualification",
  qualificationName: "Name of qualification",
  qualificationCertificate: "Highest qualification certificate",
  lngJobDesignation: "LNG job designation",
  serviceBookNumber: "Service book number",
  serviceBookDocument: "Service book copy",
  armsLicenseNumber: "Arms licence number",
  armsLicenseDocument: "Arms licence copy",
  passportCountryName: "Passport country",
  passportDocument: "Passport copy",
  district: "District",
  panNumber: "PAN number",
  aadharNumber: "Aadhaar number",
  nationality: "Nationality",
  identificationMark: "Identification mark",
  heightCm: "Height",
  weightKg: "Weight",
  identityProofType: "Identity proof type",
  identityProofNumber: "Identity proof number",
  identityProofUrlFront: "Identity proof — front",
  identityProofUrlBack: "Identity proof — back",
  addressProofType: "Address proof type",
  addressProofNumber: "Address proof number",
  addressProofUrlFront: "Address proof — front",
  addressProofUrlBack: "Address proof — back",
  aadharCardDocument: "Aadhaar copy",
  aadharCardDocumentBack: "Aadhaar back copy",
  panCardDocument: "PAN card copy",
  signatureUrl: "Signature",
  policeClearanceCertificate: "Police clearance certificate",
  epfUanNumber: "EPF UAN number",
  esicNumber: "ESIC number",
  bankAccountNumber: "Bank account number",
  ifscCode: "IFSC code",
  bankName: "Bank name",
  branchName: "Branch name",
  bankPassbookStatement: "Bank passbook or statement",
  fullAddress: "Current address",
  emailAddress: "Email address",
  phoneNumber: "Mobile number",
  legacyUniqueId: "Existing LNG ID",
  termsAndConditions: "Terms and declaration",
  aadhaarConsentAccepted: "Aadhaar consent",
  guardUndertakingAccepted: "Guard undertaking consent",
};

export function getEnrollmentFieldLabel(field: string) {
  return ENROLLMENT_FIELD_LABELS[field] ?? field;
}
