export type EnrollmentHint = { english: string; malayalam: string };

/** Short, plain-language help shown beside the enrollment step currently open. */
export const ENROLLMENT_HINTS: Record<string, EnrollmentHint> = {
  joiningDate: { english: "Enter your actual first working day.", malayalam: "നിങ്ങൾ ജോലിയിൽ പ്രവേശിച്ച യഥാർത്ഥ ആദ്യ തീയതി നൽകുക." },
  clientName: { english: "Select the client/site where you will be deployed.", malayalam: "നിങ്ങളെ നിയമിക്കുന്ന ക്ലയന്റ് അല്ലെങ്കിൽ സൈറ്റ് തിരഞ്ഞെടുക്കുക." },
  resourceIdNumber: { english: "Enter the client-issued resource ID when required.", malayalam: "ആവശ്യപ്പെട്ടാൽ ക്ലയന്റ് നൽകിയ റിസോഴ്‌സ് ഐഡി നൽകുക." },
  profilePicture: { english: "Upload a recent, clear passport-size photo.", malayalam: "സമീപകാലത്തെ വ്യക്തമായ പാസ്‌പോർട്ട് സൈസ് ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക." },
  fullNameInput: { english: "Enter your full name exactly as on your official record.", malayalam: "ഔദ്യോഗിക രേഖയിൽ ഉള്ളതുപോലെ മുഴുവൻ പേര് എഴുതുക." },
  firstName: { english: "Enter your given name.", malayalam: "നിങ്ങളുടെ പേര് നൽകുക." },
  lastName: { english: "Enter your family name or surname.", malayalam: "കുടുംബപ്പേര് അല്ലെങ്കിൽ സർനെയിം നൽകുക." },
  fatherName: { english: "Enter your father’s full name as on your proof.", malayalam: "രേഖയിൽ ഉള്ളതുപോലെ പിതാവിന്റെ മുഴുവൻ പേര് നൽകുക." },
  motherName: { english: "Enter your mother’s full name.", malayalam: "മാതാവിന്റെ മുഴുവൻ പേര് നൽകുക." },
  dateOfBirth: { english: "Use the date shown on your official proof.", malayalam: "ഔദ്യോഗിക രേഖയിൽ കാണുന്ന ജനനത്തീയതി നൽകുക." },
  gender: { english: "Select the option that describes you.", malayalam: "നിങ്ങൾക്ക് അനുയോജ്യമായ ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക." },
  maritalStatus: { english: "Select your current marital status.", malayalam: "നിലവിലെ വൈവാഹിക സ്ഥിതി തിരഞ്ഞെടുക്കുക." },
  spouseName: { english: "If married, enter your spouse’s full name.", malayalam: "വിവാഹിതനാണെങ്കിൽ പങ്കാളിയുടെ മുഴുവൻ പേര് നൽകുക." },
  educationalQualification: { english: "Select your highest completed qualification.", malayalam: "പൂർത്തിയാക്കിയ ഏറ്റവും ഉയർന്ന വിദ്യാഭ്യാസ യോഗ്യത തിരഞ്ഞെടുക്കുക." },
  otherQualification: { english: "Describe the qualification if you chose other.", malayalam: "മറ്റുള്ളത് തിരഞ്ഞെടുത്താൽ യോഗ്യതയുടെ പേര് എഴുതുക." },
  lngJobDesignation: { english: "Select the designation for the LNG site.", malayalam: "LNG സൈറ്റിലെ തസ്തിക തിരഞ്ഞെടുക്കുക." },
  serviceBookNumber: { english: "Enter the service book number if your designation requires it.", malayalam: "തസ്തികയ്ക്ക് ആവശ്യമാണെങ്കിൽ സർവീസ് ബുക്ക് നമ്പർ നൽകുക." },
  serviceBookDocument: { english: "Upload the service book page clearly.", malayalam: "സർവീസ് ബുക്ക് പേജ് വ്യക്തമായി അപ്‌ലോഡ് ചെയ്യുക." },
  armsLicenseNumber: { english: "Enter the valid arms licence number when applicable.", malayalam: "ബാധകമാണെങ്കിൽ സാധുവായ ആയുധ ലൈസൻസ് നമ്പർ നൽകുക." },
  armsLicenseDocument: { english: "Upload the valid arms licence copy.", malayalam: "സാധുവായ ആയുധ ലൈസൻസിന്റെ പകർപ്പ് അപ്‌ലോഡ് ചെയ്യുക." },
  passportCountryName: { english: "Enter the passport country only when applicable.", malayalam: "ബാധകമാണെങ്കിൽ മാത്രം പാസ്‌പോർട്ട് നൽകിയ രാജ്യം നൽകുക." },
  passportDocument: { english: "Upload the passport copy when passport details are provided.", malayalam: "പാസ്‌പോർട്ട് വിവരങ്ങൾ നൽകിയാൽ അതിന്റെ പകർപ്പ് അപ്‌ലോഡ് ചെയ്യുക." },
  district: { english: "Select or type your current district of residence.", malayalam: "ഇപ്പോൾ താമസിക്കുന്ന ജില്ല തിരഞ്ഞെടുക്കുകയോ എഴുതുകയോ ചെയ്യുക." },
  panNumber: { english: "Enter the 10-character PAN exactly as printed.", malayalam: "PAN കാർഡിൽ അച്ചടിച്ചിരിക്കുന്നതുപോലെ 10 അക്ഷര/അക്ക നമ്പർ നൽകുക." },
  aadharNumber: { english: "Enter the 12-digit Aadhaar number; it is used only for ESIC/EPF and statutory processing.", malayalam: "12 അക്ക ആധാർ നമ്പർ നൽകുക; ESIC, EPF, നിയമപരമായ നടപടികൾക്കായി മാത്രം ഉപയോഗിക്കും." },
  nationality: { english: "Enter your nationality as shown in your records.", malayalam: "രേഖകളിൽ ഉള്ളതുപോലെ ദേശീയത നൽകുക." },
  identificationMark: { english: "Describe a visible identification mark.", malayalam: "കാണാൻ കഴിയുന്ന തിരിച്ചറിയൽ അടയാളം വിവരിക്കുക." },
  heightCm: { english: "Enter your height in centimetres.", malayalam: "ഉയരം സെന്റിമീറ്ററിൽ നൽകുക." },
  weightKg: { english: "Enter your weight in kilograms.", malayalam: "ഭാരം കിലോഗ്രാമിൽ നൽകുക." },
  identityProofType: { english: "Choose one identity proof: PAN, Voter ID, Driving Licence, Passport, School Certificate, or Birth Certificate.", malayalam: "തിരിച്ചറിയൽ രേഖയായി PAN, Voter ID, Driving Licence, Passport, School Certificate, അല്ലെങ്കിൽ Birth Certificate എന്നിവയിൽ ഒന്ന് തിരഞ്ഞെടുക്കുക." },
  identityProofNumber: { english: "Enter the number printed on the selected identity proof.", malayalam: "തിരഞ്ഞെടുത്ത തിരിച്ചറിയൽ രേഖയിലെ നമ്പർ നൽകുക." },
  identityProofUrlFront: { english: "Upload the front side of the identity proof.", malayalam: "തിരിച്ചറിയൽ രേഖയുടെ മുൻവശം അപ്‌ലോഡ് ചെയ്യുക." },
  identityProofUrlBack: { english: "Upload the back side of the identity proof.", malayalam: "തിരിച്ചറിയൽ രേഖയുടെ പിൻവശം അപ്‌ലോഡ് ചെയ്യുക." },
  addressProofType: { english: "Choose a different address proof: Voter ID, Passport, or Driving Licence.", malayalam: "തിരിച്ചറിയൽ രേഖയിൽ നിന്ന് വ്യത്യസ്തമായി Voter ID, Passport, അല്ലെങ്കിൽ Driving Licence വിലാസ രേഖയായി തിരഞ്ഞെടുക്കുക." },
  addressProofNumber: { english: "Enter the number printed on the selected address proof.", malayalam: "തിരഞ്ഞെടുത്ത വിലാസ രേഖയിലെ നമ്പർ നൽകുക." },
  addressProofUrlFront: { english: "Upload the front side of the address proof.", malayalam: "വിലാസ രേഖയുടെ മുൻവശം അപ്‌ലോഡ് ചെയ്യുക." },
  addressProofUrlBack: { english: "Upload the back side of the address proof.", malayalam: "വിലാസ രേഖയുടെ പിൻവശം അപ്‌ലോഡ് ചെയ്യുക." },
  aadharCardDocument: { english: "Upload a clear self-attested Aadhaar copy for ESIC/EPF only.", malayalam: "ESIC, EPF ആവശ്യങ്ങൾക്കായി മാത്രം വ്യക്തമായ സ്വയം സാക്ഷ്യപ്പെടുത്തിയ ആധാർ പകർപ്പ് അപ്‌ലോഡ് ചെയ്യുക." },
  panCardDocument: { english: "Upload the PAN copy when required for the selected client.", malayalam: "തിരഞ്ഞെടുത്ത ക്ലയന്റിന് ആവശ്യമായാൽ PAN കാർഡിന്റെ പകർപ്പ് അപ്‌ലോഡ് ചെയ്യുക." },
  signatureUrl: { english: "Sign on white paper and upload a clear image.", malayalam: "വെളുത്ത പേപ്പറിൽ ഒപ്പിട്ട് വ്യക്തമായ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക." },
  policeClearanceCertificate: { english: "Upload the PCC if available or requested.", malayalam: "PCC ലഭ്യമാണെങ്കിൽ അല്ലെങ്കിൽ ആവശ്യപ്പെട്ടാൽ അപ്‌ലോഡ് ചെയ്യുക." },
  epfUanNumber: { english: "Enter your existing EPF UAN, if any.", malayalam: "നിലവിലുള്ള EPF UAN ഉണ്ടെങ്കിൽ നൽകുക." },
  esicNumber: { english: "Enter your existing ESIC number, if any.", malayalam: "നിലവിലുള്ള ESIC നമ്പർ ഉണ്ടെങ്കിൽ നൽകുക." },
  bankAccountNumber: { english: "Enter the bank account used for salary credit.", malayalam: "ശമ്പളം ലഭിക്കുന്ന ബാങ്ക് അക്കൗണ്ട് നമ്പർ നൽകുക." },
  ifscCode: { english: "Enter the 11-character IFSC from your bank document.", malayalam: "ബാങ്ക് രേഖയിലെ 11 അക്ഷര/അക്ക IFSC നൽകുക." },
  bankName: { english: "Enter the full bank name.", malayalam: "ബാങ്കിന്റെ മുഴുവൻ പേര് നൽകുക." },
  branchName: { english: "Enter the branch name shown on the bank proof.", malayalam: "ബാങ്ക് രേഖയിൽ കാണുന്ന ശാഖയുടെ പേര് നൽകുക." },
  bankPassbookStatement: { english: "Upload a clear passbook or statement showing account details.", malayalam: "അക്കൗണ്ട് വിവരങ്ങൾ കാണുന്ന വ്യക്തമായ പാസ്‌ബുക്ക് അല്ലെങ്കിൽ സ്റ്റേറ്റ്മെന്റ് അപ്‌ലോഡ് ചെയ്യുക." },
  fullAddress: { english: "Enter your complete current address, including PIN code.", malayalam: "PIN കോഡ് ഉൾപ്പെടെയുള്ള പൂർണ്ണമായ നിലവിലെ വിലാസം നൽകുക." },
  emailAddress: { english: "Enter an email you can access for official updates.", malayalam: "ഔദ്യോഗിക അറിയിപ്പുകൾ ലഭിക്കാൻ നിങ്ങൾക്ക് ഉപയോഗിക്കാനാകുന്ന ഇമെയിൽ നൽകുക." },
  phoneNumber: { english: "Enter your active 10-digit mobile number.", malayalam: "നിലവിൽ ഉപയോഗിക്കുന്ന 10 അക്ക മൊബൈൽ നമ്പർ നൽകുക." },
  legacyUniqueId: { english: "Use the existing LNG ID only when one was already assigned.", malayalam: "മുമ്പ് നൽകിയ LNG ഐഡി ഉണ്ടെങ്കിൽ മാത്രം നൽകുക." },
  termsAndConditions: { english: "Read the terms, duties, verification, and statutory-rights notice before accepting.", malayalam: "അംഗീകരിക്കുന്നതിന് മുമ്പ് നിബന്ധനകൾ, ചുമതലകൾ, പരിശോധന, നിയമപരമായ അവകാശങ്ങൾ എന്നിവ വായിക്കുക." },
  aadhaarConsentAccepted: { english: "Consent is limited to ESIC, EPF, and related statutory processing through official systems.", malayalam: "ഔദ്യോഗിക സംവിധാനങ്ങളിലൂടെ ESIC, EPF, ബന്ധപ്പെട്ട നിയമപരമായ നടപടികൾക്കായി മാത്രം സമ്മതം നൽകുക." },
  guardUndertakingAccepted: { english: "Read and accept the Guard Undertaking; it does not waive your statutory rights.", malayalam: "Guard Undertaking വായിച്ച് അംഗീകരിക്കുക; നിങ്ങളുടെ നിയമപരമായ അവകാശങ്ങൾ ഇതിലൂടെ നഷ്ടപ്പെടുന്നില്ല." },
};

export function getEnrollmentHint(field: string) {
  return ENROLLMENT_HINTS[field];
}
