import crypto from "node:crypto";

const QR_SECRET = process.env.CISS_QR_SECRET || process.env.NEXT_PUBLIC_FIREBASE_API_KEY || "ciss-default-qr-secret";

function getHmacKey(): string {
  // Derive a consistent key from the secret using SHA-256
  return crypto.createHash("sha256").update(QR_SECRET).digest("hex").slice(0, 32);
}

/**
 * Generate a signed QR token for an employee.
 * The token proves the QR code was generated by CISS and hasn't been tampered with.
 */
export function generateQrToken(
  employeeId: string,
  phoneNumber: string,
): string {
  const payload = `${employeeId}:${phoneNumber}`;
  const hmac = crypto
    .createHmac("sha256", getHmacKey())
    .update(payload)
    .digest("base64url")
    .slice(0, 16);
  return hmac;
}

/**
 * Verify that a QR token matches the expected employee data.
 */
export function verifyQrToken(
  employeeId: string,
  phoneNumber: string,
  token: string,
): boolean {
  const expected = generateQrToken(employeeId, phoneNumber);
  try {
    return crypto.timingSafeEqual(
      Buffer.from(expected, "utf-8"),
      Buffer.from(token, "utf-8"),
    );
  } catch {
    return false;
  }
}

/**
 * Build the full QR code content string with signed token.
 */
export function buildQrContent(
  employeeId: string,
  fullName: string,
  phoneNumber: string,
): string {
  const token = generateQrToken(employeeId, phoneNumber);
  return `CISS-ATTENDANCE\nEmployee ID: ${employeeId}\nName: ${fullName}\nPhone: ${phoneNumber}\nToken: ${token}`;
}

/**
 * Parse QR content and extract all fields including the token.
 */
export function parseQrContent(text: string): {
  employeeId: string | null;
  phoneNumber: string | null;
  name: string | null;
  token: string | null;
} {
  const normalized = text.replace(/\u0000/g, "").trim();
  if (!normalized) {
    return { employeeId: null, phoneNumber: null, name: null, token: null };
  }

  const employeeIdMatch = normalized.match(/Employee\s*ID\s*:\s*([^\n\r]+)/i);
  const phoneMatch = normalized.match(/Phone\s*:\s*([^\n\r]+)/i);
  const nameMatch = normalized.match(/Name\s*:\s*([^\n\r]+)/i);
  const tokenMatch = normalized.match(/Token\s*:\s*([^\n\r\s]+)/i);

  // Fallback: first line starting with CISS/
  const firstLine = normalized.split(/\r?\n/)[0]?.trim();
  const fallbackId = firstLine && /^CISS\//i.test(firstLine) ? firstLine : null;

  const phoneDigits = phoneMatch?.[1]?.replace(/\D/g, "").trim() ?? "";

  return {
    employeeId: employeeIdMatch?.[1]?.trim() ?? fallbackId,
    phoneNumber: phoneDigits.length >= 10 ? phoneDigits.slice(-10) : phoneDigits,
    name: nameMatch?.[1]?.trim() ?? null,
    token: tokenMatch?.[1]?.trim() ?? null,
  };
}
