/**
 * QR token generation and verification using Web Crypto API.
 * Works in both Node.js (18+) and browsers — no node:crypto import.
 */

const QR_SECRET =
  process.env.CISS_QR_SECRET ||
  process.env.NEXT_PUBLIC_FIREBASE_API_KEY ||
  "ciss-default-qr-secret";

let _cachedKey: CryptoKey | null = null;

async function getHmacKey(): Promise<CryptoKey> {
  if (_cachedKey) return _cachedKey;
  const encoder = new TextEncoder();
  const keyData = encoder.encode(QR_SECRET);
  _cachedKey = await crypto.subtle.importKey(
    "raw",
    keyData,
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign", "verify"]
  );
  return _cachedKey;
}

/**
 * Generate a signed QR token for an employee.
 * The token proves the QR code was generated by CISS and hasn't been tampered with.
 */
export async function generateQrToken(
  employeeId: string,
  phoneNumber: string
): Promise<string> {
  const payload = `${employeeId}:${phoneNumber}`;
  const encoder = new TextEncoder();
  const key = await getHmacKey();
  const signature = await crypto.subtle.sign("HMAC", key, encoder.encode(payload));
  const base64url = btoa(String.fromCharCode(...new Uint8Array(signature)))
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=/g, "");
  return base64url.slice(0, 16);
}

/**
 * Verify that a QR token matches the expected employee data.
 */
export async function verifyQrToken(
  employeeId: string,
  phoneNumber: string,
  token: string
): Promise<boolean> {
  const expected = await generateQrToken(employeeId, phoneNumber);
  if (expected.length !== token.length) return false;
  let result = 0;
  for (let i = 0; i < expected.length; i++) {
    result |= expected.charCodeAt(i) ^ token.charCodeAt(i);
  }
  return result === 0;
}

/**
 * Build the full QR code content string with signed token.
 */
export async function buildQrContent(
  employeeId: string,
  fullName: string,
  phoneNumber: string
): Promise<string> {
  const token = await generateQrToken(employeeId, phoneNumber);
  return `CISS-ATTENDANCE\nEmployee ID: ${employeeId}\nName: ${fullName}\nPhone: ${phoneNumber}\nToken: ${token}`;
}

/**
 * Parse QR content and extract all fields including the token.
 */
export function parseQrContent(text: string): {
  employeeId: string | null;
  phoneNumber: string | null;
  name: string | null;
  token: string | null;
} {
  const normalized = text.replace(/\u0000/g, "").trim();
  if (!normalized) {
    return { employeeId: null, phoneNumber: null, name: null, token: null };
  }

  const employeeIdMatch = normalized.match(/Employee\s*ID\s*:\s*([^\n\r]+)/i);
  const phoneMatch = normalized.match(/Phone\s*:\s*([^\n\r]+)/i);
  const nameMatch = normalized.match(/Name\s*:\s*([^\n\r]+)/i);
  const tokenMatch = normalized.match(/Token\s*:\s*([^\n\r\s]+)/i);

  // Fallback: first line starting with CISS/
  const firstLine = normalized.split(/\r?\n/)[0]?.trim();
  const fallbackId =
    firstLine && /^CISS\//i.test(firstLine) ? firstLine : null;

  const phoneDigits = phoneMatch?.[1]?.replace(/\D/g, "").trim() ?? "";

  return {
    employeeId: employeeIdMatch?.[1]?.trim() ?? fallbackId,
    phoneNumber: phoneDigits.length >= 10 ? phoneDigits.slice(-10) : phoneDigits,
    name: nameMatch?.[1]?.trim() ?? null,
    token: tokenMatch?.[1]?.trim() ?? null,
  };
}
